spring:
  application:
    name: config-server # Имя приложения, которое будет зарегистрировано в Eureka
  profiles:
    active: native # Активный профиль, используемый для загрузки конфигураций из локальных ресурсов
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/{profile}/{application} # Путь к файлам конфигураций сервисов внутри classpath

server:
  port: 0 # Порт сервера. Значение 0 означает, что порт будет назначен автоматически

management:
  endpoints:
    web:
      exposure:
        include: health,info,configprops,loggers

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5 # Интервал обновления статуса инстанса в секундах
    lease-expiration-duration-in-seconds: 10 # Время жизни инстанса в секундах до его удаления из реестра
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
  client:
    registry-fetch-interval-seconds: 5 # Интервал обновления локального реестра клиентов в секундах
    initial-instance-info-replication-interval-seconds: 3 # Задержка перед первой отправкой информации об инстансе в секундах
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/ # URL сервера Eureka для регистрации и обнаружения сервисов