server:
  port: 8082

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  application:
    name: analyzerApp
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
    show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/smarthomedb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

kafka:
  hub-consumer-properties:
    bootstrap.servers: localhost:9092
    group.id: hub-analyzer-group
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: ru.practicum.HubEventDeserializer
    auto.offset.reset: earliest
    enable.auto.commit: false
    # Настройки батчинга
    fetch.min.bytes: 100
    fetch.max.wait.ms: 500

  snapshot-consumer-properties:
    bootstrap.servers: localhost:9092
    group.id: snapshot-analyzer-group
    key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value.deserializer: ru.practicum.SensorsSnapshotDeserializer
    auto.offset.reset: earliest
    enable.auto.commit: false
    # Настройки батчинга
    fetch.min.bytes: 100
    fetch.max.wait.ms: 500

  topics:
    TELEMETRY_SENSORS: telemetry.sensors.v1
    TELEMETRY_SNAPSHOTS: telemetry.snapshots.v1
    TELEMETRY_HUBS: telemetry.hubs.v1

logging:
  level:
    # Для обработчика
    ru.practicum.service: DEBUG
    # Для Spring
    org.springframework:
      orm.jpa: INFO
      transaction: INFO
      transaction.interceptor: TRACE
      orm.jpa.JpaTransactionManager: DEBUG

---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:h2:mem:smarthome-db
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console:
    enabled: true
    path: /stats-h2-console