grpc:
  server:
    port: 59091

spring:
  kafka:
    bootstrap-servers: localhost:9092

kafka:
  producer-properties:
    bootstrap.servers: localhost:9092
    key.serializer: org.apache.kafka.common.serialization.StringSerializer
    value.serializer: ru.practicum.GeneralAvroSerializer
    # Настройки батчинга
    batch.size: 16384                    # Максимальный объем батча в байтах (16KB)
    linger.ms: 100                       # Максимальное время ожидания в ms
    buffer.memory: 33554432              # Общий объем буфера в байтах (32MB)
    max.request.size: 1048576            # Максимальный размер запроса в байтах (1MB)
    compression.type: none               # Тип сжатия (none, gzip, snappy, lz4, zstd)

  topics:
    TELEMETRY_SENSORS: telemetry.sensors.v1
    TELEMETRY_SNAPSHOTS: telemetry.snapshots.v1
    TELEMETRY_HUBS: telemetry.hubs.v1

logging:
  level:
    # Для контроллера
    ru.practicum.controller: DEBUG
    # Для обработчика
    ru.practicum.service.handler: DEBUG
    # Для gRPC
    net.devh.boot.grpc: INFO
    # Для Spring
    org.springframework: INFO